name: footbal_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # packages
  flutter_screenutil: ^5.9.0
  provider: ^6.1.1
  dio: ^5.4.0
  xml: ^6.5.0
  html: ^0.15.4
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2

flutter_launcher_icons:
  android: "app_icon"
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  background_image: assets/images/splash_screen_back.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
